title: ConnorBP ./ Segfault
repository: ConnorBP/segfault.site
url: https://segfault.site
baseurl: ""
exclude: [bin, tests, tmp, vendor]
description: Software engineer and security researcher building systems, games, and developer tools.
show_downloads: false
google_analytics:
plugins:
- github-pages